language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "eNs1gt+mvt1pyANLXGn5TVgd8hk0wDDbPx5r/BD+ba5OygXdxt2FqMIlRgKOXIbaewq+vqEu68cptffu2o8TFrWWF05Wfb6nBgHTcPNnr/hjnHInUg/2C1J1SYmLfGcoLX8TY4wWWvzr5zuxfAEkieAEkWVl92ack4jyggGnJiydXnC0iN/saHnNN6GE7HDkU/p1BYTHsOh99uYvdx7bx3f8zdWpLNbGMCfr3S3HpQR6oIl7pjzaxrXIIYWIUF+ix3wCMhQDNf5og+H63KeE5PciChjeJ+/Xt12/mEG7mGjL4qHGilDj7EqgtoV8n92MdhR/Xbb4NoY7zteSUs5QTWOFBuTm0oagr1kdmMxovWQXjSjGt/ybfT2syYYK5o/foteyI8oZ66b74VJCkjxF9NBj+uIznB9yN6riMSf83g0DHyfHC3sj+LEUzvQR9ksRoSKYaCKUBiJ1088aWKQAq9OgoHnH6nMogqCcweZbMBydOpaBJvWrY0UnK4vPNu83K46fmn13nRNbYFgUSPx22rAtLbcIfNXEwFwoEMK0J3RjmGxiNuC26WbKHIlu/zB3CXCa9Icou/vOuSBMZvqeyimLwRRbzNWDSxVluOeex684Ek1KBhyCvJd+8mtfBtVifqc297xKCG4up1cT2t+scgSVmGPc91lPAB8YP/GMy+8="