language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "zMjt8RRuSAeC2W9B7StvJE7l6CLPFGowY70hhuJckD9hH/EUgOzykUKeVeoDJAisqEkDMl3+slAzNTs9UNCIHdOwNYufDGLUmlJq/WikdJPgl7PhnYD5sAZz6uY+l6GDIjNIMxhd0PnvregYWc0Vy+H/Ea7YNsTU9Bwp/E6QKfj2oZJOFQFXzFXorZ19KTo3RH9FzQWVAHmctnLTe6sfqoC+UtjfeFmaxjo2c/v4n1cJGrtZNmBk1MG+VNEjBTygshv9jW+EZksVTsaZQ95NMOxN5iXGbeAO2Mjnq1xzIW51uJZc0JksNLtOLsPwLFO7SvzLyx+7Amq+aJrB55wtaTbWGHYOB7vt/QUtZPWB6knwF0r6XqoyLZDYwjA+mPAxYG7Mx+kiC9nQl7pB065ViwQnYa75zMCF11Uckd7i8c3lyNnJ8s3mb6PPMCaT1efGXcDEK1SwU9xWrWPQG0Yq+UckCMhr2LNFKRgkOnEzK7JtdDq1MwIng1xe33Zxyhscg6TPCSjvuzxfqK0M/KTYvlpyV+Q/HH1OkQHciP11ZYGHfl7VeIE0pfsfavNxNz/lwul5Z7N0h64J8PA5+kqFFSlFwqDYH0yVTuy8tjYs0x7D77fG2Dn2QQMjpBz2XjfpvHXTORsKwl3zpEH+Iw3BW3Xo5X7GLjbMBRGMlLIho5E="
